<p>
  Handles errors in an observable sequence. Remember to return an observable
  from the catchError function.
</p>
